export { default as CompanyIntro } from './CompanyIntro'
export { default as VisionMission } from './VisionMission'
export { default as Timeline } from './Timeline'
export { default as TeamSection } from './TeamSection'
export { default as AboutStats } from './AboutStats'
